source "https://rubygems.org"

ruby "2.6.2"

gem "middleman", "~> 4.3"
gem "middleman-autoprefixer", "~> 2.10"
gem "middleman-livereload", "~> 3.4"
gem "middleman-blog", "~> 4.0"

gem "haml", "~> 5.1"
gem "builder", "~> 3.2"
gem "jbuilder", "~> 2.9"
gem "tilt-jbuilder", "~> 0.7.1"
gem "slim", "~> 4.0"
gem "kramdown", "~> 1.17"
